#Tomcat server
server:
  port: 9000
  
#Jsp
spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  devtools:
    livereload:
      enabled: true
      
#Mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tea
    username: junbro
    password: 1234

#Mybatis
mybatis:
  type-aliases-package: boot.guest.*
  mapper-locations:
  - /mapper/**/*.xml